---
# This playbook sets up whole stack.
 
- name: Configurations to "dockers" host
  hosts: docker
  # remote_user: ubuntu # take from inventory or cmd
  become: yes
  vars_files:
    - vars/default.yml
  roles:
    - setup
    - reception