---
# This playbook contains all actions that will be run on "local" host.
 
# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system
 
# Import docker tasks
- name: Import user task
  include_tasks: 01_user.yaml
  tags:
    - initial

#- name: Hostname 02
#  include_tasks: 02_hostname.yaml

- name: init_setup.yaml 03
  include_tasks: 03_init_setup.yaml

- name: docker.yaml 04
  include_tasks: 04_docker.yaml


# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - system
 
# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - system